Repository massalabs/massa-as-sdk, pull requests merged in 2022-11, with the labels that each got.

#21 add npm dev publish workflow
  .github/workflows/node.js.yml
  .github/workflows/npm-publish-dev.yml
  .github/workflows/npm-publish.yml
  scripts/enable-git-ssh.sh
  scripts/publish-dev.sh
Labels: action:merge

#42 fixes toU32 length check
  assembly/std/__tests__/arguments.spec.ts
  assembly/std/arguments.ts
Labels: bug, action:merge

#60 export NFT
  assembly/NFT/index.ts
  assembly/index.ts
Labels: bug, action:merge

#71 Aargs: serialize boolean
  .editorconfig
  assembly/std/__tests__/arguments.spec.ts
  assembly/std/address.ts
  assembly/std/arguments.ts
Labels: enhancement, action:merge, P3

#80 79 change filetob64 function for new transformer
  assembly/std/index.ts
Labels: action:merge

#73 solve nft issue
  assembly/NFT/NFT.ts
  assembly/NFT/__tests__/NFT.spec.ts
Labels: action:merge
